name = "easy-seo-api"
main = "worker.js"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB" # accessible in your Worker via env.DB
database_name = "easy-seo-layouts-db"
# This is a placeholder for local development. In a deployed environment,
# this ID would typically be populated from a secret or environment variable.
database_id = "a-placeholder-id-for-local-dev"

[dev]
port = 8787
local_protocol = "http"
host = "localhost"